qcacld-3.0: Fix another warning
../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/wmi/src/wmi_unified_api.c:348:48: error: argument 2 of type 'uint8_t *' {aka 'unsigned char *'} declared as a pointer [-Werror=array-parameter=]
  348 |                                       uint8_t *peer_addr,
      |                                       ~~~~~~~~~^~~~~~~~~
In file included from ../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/wmi/inc/wmi_unified_priv.h:26,
                 from ../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/wmi/src/wmi_unified_api.c:19:
../drivers/staging/qcacld-3.0/../qca-wifi-host-cmn/wmi/inc/wmi_unified_api.h:1012:47: note: previously declared as an array 'uint8_t[6]' {aka 'unsigned char[6]'}
 1012 |                                       uint8_t macaddr[QDF_MAC_ADDR_SIZE],
      |                                       ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: CloudedQuartz <ravenklawasd@gmail.com>

# Conflicts:
#	drivers/staging/qca-wifi-host-cmn/wmi/src/wmi_unified_api.c