qcacld-3.0: Fix another warning
../drivers/staging/qcacld-3.0/core/mac/src/sys/legacy/src/utils/src/parser_api.c:5871:28: error: argument 3 of type 'uint8_t[3]' {aka 'unsigned char[3]'} with mismatched bound [-Werror=array-parameter=]
 5871 |                    uint8_t mdie[SIR_MDIE_SIZE])
      |                    ~~~~~~~~^~~~~~~~~~~~~~~~~~~
In file included from ../drivers/staging/qcacld-3.0/core/mac/src/pe/include/sch_global.h:36,
                 from ../drivers/staging/qcacld-3.0/core/mac/inc/ani_global.h:28,
                 from ../drivers/staging/qcacld-3.0/core/mac/src/sys/legacy/src/utils/src/parser_api.c:31:
../drivers/staging/qcacld-3.0/core/mac/src/include/parser_api.h:1028:28: note: previously declared as 'uint8_t[]' {aka 'unsigned char[]'}
 1028 |                    uint8_t mdie[]);
      |                    ~~~~~~~~^~~~~~

Signed-off-by: CloudedQuartz <ravenklawasd@gmail.com>

# Conflicts:
#	drivers/staging/qcacld-3.0/core/mac/src/include/parser_api.h